#! /bin/sh

picom -b &
wmname LG3D &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
sxhkd &

nm-applet &
pamac-tray &
xfce4-power-manager &
killall clipit ; clipit &

bspc monitor eDP-1 -d I II III IV V
if [[ "$(xrandr --listmonitors | grep DP-2)" ]]; then
	bspc monitor DP-2  -d VI VII VIII IX X
else
	bspc monitor eDP-1 -a VI VII VIII IX X
fi

bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.52

bspc config single_monocle 	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true
bspc config pointer_follows_monitor 	true

bspc rule -a polybar border=off manage=off

bspc rule -a Pavucontrol 			state=floating
bspc rule -a Pamac-manager 			state=floating
bspc rule -a Galculator 			state=floating

bspc rule -a firefox 				desktop='^1'  follow=on
bspc rule -a firefoxdeveloperedition 		desktop='^2'  follow=on
bspc rule -a "Microsoft Teams - Preview" 	desktop='^3'  follow=on
bspc rule -a jetbrains-idea 			desktop='^10' follow=on

bspc config external_rules_command "`dirname "$0"`/external_rules"
