#! /bin/sh

#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -b &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
sxhkd &

nm-applet &
pamac-tray &
xfce4-power-manager &
killall clipit ; clipit &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           6

bspc config split_ratio          0.52

bspc config single_monocle 	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true
bspc config pointer_follows_monitor 	true

bspc rule -a polybar border=off manage=off

bspc rule -a Pavucontrol state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a Galculator state=floating

bspc config external_rules_command "`dirname "$0"`/external_rules"

#bspc rule -a zenity:Timer state=floating sticky=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
