#! /bin/sh

wid=$1
class=$2
#instance=$3
#consequences=$4

case "$class" in
	[Zz]enity)
		[[ "$(xtitle "$wid")" == "Timer" ]] && echo "sticky=on"
		;;
	[Ff]irefox)
		[[ "$(xtitle "$wid")" == "Picture-in-Picture" ]] && echo "state=floating sticky=on center=on"
		;;
esac
